version: "3.8"

services:
  wordpress:
    image: bitnami/wordpress:latest
    container_name: wordpress
    ports:
      - "8080:8080"
    environment:
      WORDPRESS_DATABASE_HOST: db
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DATABASE_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DATABASE_PASSWORD: ${WORDPRESS_DB_PASSWORD}

      # Admin user credentials
      WORDPRESS_USERNAME: ${WORDPRESS_USERNAME}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}

    volumes:
      - wp_data:/bitnami/wordpress
    depends_on:
      - db
    networks:
      - wp-network
    restart: unless-stopped

  db:
    image: bitnami/mariadb:latest
    container_name: db
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${WORDPRESS_DB_NAME}
      MARIADB_USER: ${WORDPRESS_DB_USER}
      MARIADB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - db_data:/bitnami/mariadb
    networks:
      - wp-network
    restart: unless-stopped

volumes:
  wp_data:
  db_data:

networks:
  wp-network:
